### PR TITLE
updated artist alley link

### PR DESCRIPTION
**Pull request by sbphantom**

### CODE REVIEW

**Comment by andrewhong04** [comment]
Looks like there is a merge conflict. Could you try resolving it?

**Comment by sbphantom** [comment]
hope i did that right

**Comment by andrewhong04** [comment]
Looks like there were a few changes that weren't supposed to be made in this pull request. Chloe has requested an immediate change so I'll be taking over from here.

**Comment by andrewhong04** [comment]
I cherry-picked the commit from your branch to the main branch; should be all good now. https://github.com/rutgersesports/rutgersesports.club/commit/0630d3028872358bef77a56289892baefd08add3

**Pull request closed without merging**
